version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: otp-auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/otpdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET_KEY: lkhkgjhfgdxfhjklmnbfghbvfyhjkoiuhgfrtyhjiuygf
      JWT_EXPIRATION_TIME: 86400000
    networks:
      - otp-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otpdb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - otp-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge

volumes:
  db-data:
    driver: local